# Site settings
baseurl = "https://snollygolly.github.io/qrafty-web/"
languageCode = "en-us"
title = "QraftyToken"
theme = "hugo-stellar-theme"

googleAnalytics = "" #put your google-analytics ID here

[params]
  [params.header]
    title = "QraftyToken"
    description = 'A qrafty crypto token to reward great work ğŸ¦ğŸ™ŒğŸ’ğŸš€'
    image = "images/qrafty-logo.svg"

  [[params.navigation]]
    name = "Overview"
    href = "#intro"

  [[params.navigation]]
    name = "Contract Address"
    href = "#contract-address"

  [[params.navigation]]
    name = "About QraftyToken"
    href = "#about-qrafty"

  [[params.navigation]]
    name = "Contributing"
    href = "#contributing"

  [params.intro]
    title = "QraftyToken"
    description = "We are building the token that will power the future of rewards for praise. Collect Qrafty tokens and trade your way to a ticket to the moon! ğŸš€ğŸŒ•"
    image = "images/moon-rocket.jpg"

  [[params.section]]
    id = "contract-address"
    title = "Contract Address"
    description = "QraftyToken is a BEP-20 token. You can check the offical bscscan here: https://bscscan.com/token/0xad70364909a8a927caa5fc0826686500c7709c93"

  [[params.section]]
    id = "about-qrafty"
    title = "About QraftyToken"
    description = "QraftyToken is a decentralized cryptocurrency that was created to become the token of reference for the sending praises to coworkers. Our plan for the token is to become a universal means of payment for great work by teamates within any organization."


  [[params.section]]
    id = "contributing"
    title = "Contributing"
    description = "Contributions welcome @ https://github.com/snollygolly/qrafty-token"

  [params.footer]

    # copyright
    [params.footer.copyright]
      enable = true
      text = "Â© QraftyToken, Design: [HTML5UP](//html5up.net)"
